default: Prepare TestRun

YEAR    = 2024
DATE    = 0909
DMY     = ${YEAR}${DATE}
DYMC    = /eos/cms/store/group/phys_heavyions/chenyi/PbPb2018/Forest/DYJetsToLL_MLL-50_TuneCP5_HydjetDrumMB_5p02TeV-amcatnloFXFX-pythia8/HINPbPbSpring21MiniAOD-mva98_112X_upgrade2018_realistic_HI_v9-v1/MINIAODSIM/DYJetsToLL_MLL-50_TuneCP5_HydjetDrumMB_5p02TeV-amcatnloFXFX-pythia8/20240605_ZHadronMCDY/240605_151412/0000/
CERNBOX = /eos/home-p/pchou/figs/ZHadron2024/TrkEff/${DMY}/
#EOSBase = /eos/cms/store/group/phys_heavyions/pchou/HIZHadron2024/Corrections/20240715_TrkEff/${DMY}/
EOSBase = /eos/home-p/pchou/HIZHadron2024/Corrections/20240715_TrkEff/${DMY}/
AFSBase = /afs/cern.ch/user/p/pchou/HIZHadron2024/Corrections/20240715_TrkEff/
PPMC    = /eos/cms/store/group/phys_heavyions/chenyi/pp2017/Forest/DYJetsToLL_MLL-50_TuneCP5_5020GeV-amcatnloFXFX-pythia8/RunIIpp5Spring18DR-94X_mc2017_realistic_forppRef5TeV-v2/AODSIM/DYJetsToLL_MLL-50_TuneCP5_5020GeV-amcatnloFXFX-pythia8/20231020_ZHadronMLLWithMuTreePP/231020_152224/0000/
MBMC    = /eos/cms/store/group/phys_heavyions/chenyi/Samples/store/user/mitaylor/PhotonJet/MinBias_Hydjet_Drum5F_2018_5p02TeV/HINPbPbSpring21MiniAOD-NoPUmva98_112X_upgrade2018_realistic_HI_v9-v1/MINIAODSIM/MinBias_Hydjet_Drum5F_2018_5p02TeV/20230127PbPbMCMB/230127_211118/

TrackResidualPathPbPb="${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_0_20.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_20_60.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_60_100.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_100_200.root"
TrackResidualPathPbPbNoZ="${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_0_20.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_20_60.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_60_100.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_100_200.root"
TrackResidualPathPbPbMB="${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_0_20.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_20_60.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_60_100.root,${ProjectBase}/CommonCode/root/20230522_TrackResidualCorrection_V9_100_200.root"
TrackResidualPathPP="${ProjectBase}/CommonCode/root/20230531_TrackResidualCorrection_V12_pp.root"

#TrackResidualPathPbPb="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_0_20.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_20_60.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_60_100.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_100_200.root"
#TrackResidualPathPbPbNoZ="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_0_20_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_20_60_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_60_100_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_100_200_NoZ.root"
#TrackResidualPathPbPbMB="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_0_20_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_20_60_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_60_100_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_100_200_MB.root"
#TrackResidualPathPP="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V1_pp.root"

#TrackResidualPathPbPb="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_0_20.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_20_60.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_60_100.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_100_200.root"
#TrackResidualPathPbPbNoZ="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_0_20_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_20_60_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_60_100_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_100_200_NoZ.root"
#TrackResidualPathPbPbMB="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_0_20_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_20_60_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_60_100_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_100_200_MB.root"
#TrackResidualPathPP="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V2_pp.root"

#TrackResidualPathPbPb="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_0_20.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_20_60.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_60_100.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_100_200.root"
#TrackResidualPathPbPbNoZ="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_0_20_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_20_60_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_60_100_NoZ.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_100_200_NoZ.root"
#TrackResidualPathPbPbMB="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_0_20_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_20_60_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_60_100_MB.root,${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_100_200_MB.root"
#TrackResidualPathPP="${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_V3_pp.root"

VERSION=V1
IFDOIter=false
IFDOHiBinShift=false

Prepare:
	ln -sf $(DYMC) DYMC
	ln -sf $(PPMC) PPMC
	ln -sf $(MBMC) MBMC

TestRun: Execute
	./Execute --Input DYMC/HiForestMiniAOD_364.root \
		--Output EffPlotsPbPb_${DATE}_0_20_${VERSION}.pdf --RootOutput TrkEffPbPb_${DATE}_0_20_${VERSION}.root --Fraction 0.7 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPb)  --DoIteration ${IFDOIter} \
		--MinHiBin 0 --MaxHiBin 20 --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	mkdir -p $(CERNBOX)
	mv EffPlotsPbPb_${DATE}_0_20_${VERSION}.pdf $(CERNBOX)


TestRunPP: Execute
	./Execute --Input `ls PPMC/* | head -n1 | tr '\n' ','` \
		--Output EffPlotsPP_${DATE}_${VERSION}.pdf --RootOutput TrkEffPP_${DATE}_${VERSION}.root --Fraction 1.00 --IsPP true \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPP) --DoIteration ${IFDOIter}  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	mkdir -p $(CERNBOX)
	mv EffPlotsPP_${DATE}_${VERSION}.pdf $(CERNBOX)

TestRunMB: Execute
	./Execute --Input `ls MBMC/* | head -n1 | tr '\n' ','` \
		--Output EffPlotsPbPbMB_${DATE}_0_20_${VERSION}.pdf --RootOutput TrkEffPbPbMB_${DATE}_0_20_${VERSION}.root --Fraction 0.2 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbMB)  --DoIteration ${IFDOIter} \
		--MinHiBin 0 --MaxHiBin 20 --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	mkdir -p $(CERNBOX)
	mv EffPlotsPbPbMB_${DATE}_0_20_${VERSION}.pdf $(CERNBOX)

TestRunAll: Execute
	./Execute --Input `ls DYMC/* | tr '\n' ','` \
		--Output AllPbPbEffPlots.pdf --RootOutput /tmp/pchou/TrkEffAll.root --Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPb) --DoIteration ${IFDOIter} \
		--MinHiBin 0 --MaxHiBin 100  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	mv /tmp/pchou/TrkEffAll.root .
	mkdir -p $(CERNBOX)
	cp AllPbPbEffPlots.pdf $(CERNBOX)

TestRunAllPP: Execute
	./Execute --Input `ls PPMC/* | tr '\n' ','` \
		--Output AllPPEffPlots.pdf --RootOutput /tmp/pchou/TrkEffAllPP.root --Fraction 1.00 --IsPP true \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPP) --DoIteration ${IFDOIter}  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	mv /tmp/pchou/TrkEffAllPP.root .
	mkdir -p $(CERNBOX)
	cp AllPPEffPlots.pdf $(CERNBOX)

Execute: DeriveTrkEff.cpp
	g++ DeriveTrkEff.cpp  -I. -I$(ProjectBase)/CommonCode/include \
		-o Execute `root-config --cflags --libs` -std=c++17 \
		$(ProjectBase)/CommonCode/library/Messenger.o \
		# $(FJExtra) $(FJCExtra)

PrepareAll: PreparePbPb PreparePbPbNoZ PrepareToRunPP PrepareMB
PreparePbPb: PrepareToRun1 PrepareToRun2 PrepareToRun3 PrepareToRun4
PreparePbPbNoZ: PrepareToRun10 PrepareToRun20 PrepareToRun30 PrepareToRun40
PrepareMB: PrepareToRunMB1 PrepareToRunMB2 PrepareToRunMB3 PrepareToRunMB4

PrepareToRun1: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPb_0_20_${VERSION}/ $(EOSBase)/PbPb_0_20_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPb)  --DoIteration ${IFDOIter} \
		--MinHiBin 0 --MaxHiBin 20  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun2: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPb_20_60_${VERSION}/ $(EOSBase)/PbPb_20_60_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPb)  --DoIteration ${IFDOIter} \
		--MinHiBin 20 --MaxHiBin 60  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun3: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPb_60_100_${VERSION}/ $(EOSBase)/PbPb_60_100_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPb)  --DoIteration ${IFDOIter} \
		--MinHiBin 60 --MaxHiBin 100  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun4: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPb_100_200_${VERSION}/ $(EOSBase)/PbPb_100_200_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPb)  --DoIteration ${IFDOIter} \
		--MinHiBin 100 --MaxHiBin 200  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun10: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPbNoZ_0_20_${VERSION}/ $(EOSBase)/PbPbNoZ_0_20_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbNoZ)  --DoIteration ${IFDOIter} \
		--MinHiBin 0 --MaxHiBin 20  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun20: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPbNoZ_20_60_${VERSION}/ $(EOSBase)/PbPbNoZ_20_60_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbNoZ)  --DoIteration ${IFDOIter} \
		--MinHiBin 20 --MaxHiBin 60  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun30: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPbNoZ_60_100_${VERSION}/ $(EOSBase)/PbPbNoZ_60_100_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbNoZ)  --DoIteration ${IFDOIter} \
		--MinHiBin 60 --MaxHiBin 100  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRun40: Execute
	bash PrepareInput.sh \
		$(DYMC) 2 LogPbPbNoZ_100_200_${VERSION}/ $(EOSBase)/PbPbNoZ_100_200_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbNoZ)  --DoIteration ${IFDOIter} \
		--MinHiBin 100 --MaxHiBin 200  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRunPP: Execute
	bash PrepareInput.sh \
		$(PPMC) 2 LogPP_${VERSION}/ $(EOSBase)/pp_${VERSION}/ \
		--Fraction 1.00 --IsPP true \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPP) --DoIteration ${IFDOIter}  --DoZSelection true --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRunMB1: Execute
	bash PrepareInput.sh \
		$(MBMC) 2 LogPbPbMB_0_20_${VERSION}/ $(EOSBase)/PbPbMB_0_20_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbMB)  --DoIteration ${IFDOIter} \
		--MinHiBin 0 --MaxHiBin 20  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRunMB2: Execute
	bash PrepareInput.sh \
		$(MBMC) 2 LogPbPbMB_20_60_${VERSION}/ $(EOSBase)/PbPbMB_20_60_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbMB)  --DoIteration ${IFDOIter} \
		--MinHiBin 20 --MaxHiBin 60  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRunMB3: Execute
	bash PrepareInput.sh \
		$(MBMC) 2 LogPbPbMB_60_100_${VERSION}/ $(EOSBase)/PbPbMB_60_100_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbMB)  --DoIteration ${IFDOIter} \
		--MinHiBin 60 --MaxHiBin 100  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

PrepareToRunMB4: Execute
	bash PrepareInput.sh \
		$(MBMC) 2 LogPbPbMB_100_200_${VERSION}/ $(EOSBase)/PbPbMB_100_200_${VERSION}/ \
		--Fraction 1.00 \
		--TrackEfficiencyPath ${ProjectBase}/CommonCode/root/ \
		--TrackResidualPath $(TrackResidualPathPbPbMB)  --DoIteration ${IFDOIter} \
		--MinHiBin 100 --MaxHiBin 200  --DoZSelection false --DoMCHiBinShift ${IFDOHiBinShift}
	condor_submit Submit.condor

Merge: MergePbPb MergePbPbNoZ MergePP MergeMB
MergePbPb: MergePbPb1 MergePbPb2 MergePbPb3 MergePbPb4
MergePbPbNoZ: MergePbPb10 MergePbPb20 MergePbPb30 MergePbPb40
MergeMB: MergePbPbMB1 MergePbPbMB2 MergePbPbMB3 MergePbPbMB4

MergePbPb1: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPb_0_20_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbEffPlots_0_20_${VERSION}.pdf \
	--RootOutput  ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_0_20.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPb) --TrackResIdx 0 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_0_20.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_0_20.err < /dev/null &

MergePbPb2: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPb_20_60_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbEffPlots_20_60_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_20_60.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPb) --TrackResIdx 1 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_20_60.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_20_60.err < /dev/null &

MergePbPb3: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPb_60_100_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbEffPlots_60_100_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_60_100.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPb) --TrackResIdx 2 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_60_100.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_60_100.err < /dev/null &

MergePbPb4: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPb_100_200_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbEffPlots_100_200_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_100_200.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPb) --TrackResIdx 3 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_100_200.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_100_200.err < /dev/null &

MergePbPb10: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbNoZ_0_20_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbNoZEffPlots_0_20_${VERSION}.pdf \
	--RootOutput  ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_0_20_NoZ.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbNoZ) --TrackResIdx 0 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_0_20_NoZ.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_0_20_NoZ.err < /dev/null &

MergePbPb20: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbNoZ_20_60_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbNoZEffPlots_20_60_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_20_60_NoZ.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbNoZ) --TrackResIdx 1 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_20_60_NoZ.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_20_60_NoZ.err < /dev/null &

MergePbPb30: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbNoZ_60_100_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbNoZEffPlots_60_100_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_60_100_NoZ.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbNoZ) --TrackResIdx 2 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_60_100_NoZ.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_60_100_NoZ.err < /dev/null &

MergePbPb40: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbNoZ_100_200_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbNoZEffPlots_100_200_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_100_200_NoZ.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbNoZ) --TrackResIdx 3 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_100_200_NoZ.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_100_200_NoZ.err < /dev/null &

MergePP: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/pp_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPPEffPlots_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_pp.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPP) --TrackResIdx 0 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_pp.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_pp.err < /dev/null &

MergePbPbMB1: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbMB_0_20_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbMBEffPlots_0_20_${VERSION}.pdf \
	--RootOutput  ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_0_20_MB.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbMB) --TrackResIdx 0 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_0_20_MB.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_0_20_MB.err < /dev/null &

MergePbPbMB2: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbMB_20_60_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbMBEffPlots_20_60_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_20_60_MB.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbMB) --TrackResIdx 1 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_20_60_MB.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_20_60_MB.err < /dev/null &

MergePbPbMB3: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbMB_60_100_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbMBEffPlots_60_100_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_60_100_MB.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbMB) --TrackResIdx 2 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_60_100_MB.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_60_100_MB.err < /dev/null &

MergePbPbMB4: ExecuteMerge
	mkdir -p $(CERNBOX) log
	./ExecuteMerge --Input "$(EOSBase)/PbPbMB_100_200_${VERSION}/*.root" \
	--Output $(CERNBOX)/AllPbPbMBEffPlots_100_200_${VERSION}.pdf \
	--RootOutput ${ProjectBase}/CommonCode/root/${DMY}_TrackResidualCorrection_${VERSION}_100_200_MB.root \
	--DoIteration ${IFDOIter} --TrackResidualPath $(TrackResidualPathPbPbMB) --TrackResIdx 3 \
	> log/${DMY}_TrackResidualCorrection_${VERSION}_100_200_MB.out 2> log/${DMY}_TrackResidualCorrection_${VERSION}_100_200_MB.err < /dev/null &

ExecuteMerge: mergeHist.cpp
	g++ mergeHist.cpp  -I. -I$(ProjectBase)/CommonCode/include \
		-o ExecuteMerge `root-config --cflags --libs` -std=c++17 \
		$(ProjectBase)/CommonCode/library/Messenger.o \
